"""Field extraction. Statements are read from table rows by label, with the page kept per field.
Invoices and bank statements go through a model when one is set, or simple rules when not."""

from __future__ import annotations

import json
import re
from collections import Counter

from pydantic import BaseModel, ValidationError

from .ingest import Document, Page
from .llm import Backend
from .numbers import normalize_number
from .schemas import SCHEMAS, BalanceSheet, CashFlow, IncomeStatement

# schema -> field -> (label regex, how to combine rows)
_P = re.IGNORECASE
RULES: dict[str, dict[str, tuple[re.Pattern, str]]] = {
    "income_statement": {
        "revenue": (re.compile(r"^(total )?(net )?(sales|revenues?)(, net)?$", _P), "first"),
        "cost_of_revenue": (re.compile(r"^total cost of (sales|revenues?)$|^cost of (sales|revenues?)$", _P), "first"),  # noqa: E501
        "gross_profit": (re.compile(r"^gross (margin|profit)$", _P), "first"),
        "operating_income": (re.compile(r"^(income|\(loss\) income|income \(loss\)) from operations$|^operating (income|profit)$", _P), "first"),  # noqa: E501
        "net_income": (re.compile(r"^net (income|earnings)( \(loss\))?$", _P), "first"),
        "eps_diluted": (re.compile(r"^diluted( \(.*\))?$", _P), "eps"),
    },
    "balance_sheet": {
        "cash": (re.compile(r"^cash and cash equivalents$", _P), "first"),
        "total_current_assets": (re.compile(r"^total current assets$", _P), "first"),
        "total_assets": (re.compile(r"^total assets$", _P), "first"),
        "total_current_liabilities": (re.compile(r"^total current liabilities$", _P), "first"),
        "total_liabilities": (re.compile(r"^total liabilities$", _P), "first"),
        "total_equity": (re.compile(r"^total (shareholders|stockholders)[’'`]? ?(equity|deficit)( \(deficit\))?$", _P), "first"),  # noqa: E501
        "total_debt": (re.compile(r"^(commercial paper|term debt|current portion of long-term debt|long-term debt|notes payable|loans? payable)\b", _P), "sum"),  # noqa: E501
    },
    "cash_flow": {
        "operating_cash_flow": (re.compile(r"^(net )?cash (provided by|generated by|from)( \(used in\))? operating activities", _P), "first"),  # noqa: E501
        "capital_expenditures": (re.compile(r"^(payments for acquisition of|purchases? of|additions to) property", _P), "capex"),  # noqa: E501
    },
}  # fmt: skip
PRIOR = {  # field -> prior-year field, read from the second number in the row
    "revenue": "revenue_prior",
    "operating_income": "operating_income_prior",
    "net_income": "net_income_prior",
}
STATEMENTS = {
    "income_statement": IncomeStatement,
    "balance_sheet": BalanceSheet,
    "cash_flow": CashFlow,
}


def _row_numbers(row: list[str]) -> list[float]:
    out = []
    for c in row[1:]:
        v = normalize_number(c)
        if v is not None:
            out.append(v)
    return out


def _match_rows(schema: str, page: Page):
    """Yield (field, mode, label, numbers) for each table row that matches a rule."""
    for table in page.tables:
        for row in table:
            if len(row) < 2:
                continue
            label = re.sub(r"\s*\((note|notes)\b[^)]*\)?", "", row[0]).strip(" :")
            nums = _row_numbers(row)
            if not nums:
                continue
            for fld, (rx, mode) in RULES[schema].items():
                if rx.search(label):
                    yield fld, mode, label, nums


def score_page(schema: str, page: Page) -> int:
    return len({m[0] for m in _match_rows(schema, page)})


def detect_unit(doc: Document, page: Page) -> str:
    rx = re.compile(r"\bin (thousands|millions|billions)\b", _P)
    near = [p for p in doc.pages if abs(p.number - page.number) <= 2]
    for pool in (near, doc.pages):
        found = Counter(m.group(1).lower() for p in pool for m in rx.finditer(p.content))
        if found:
            return found.most_common(1)[0][0]
    return "units"


def doc_facts(doc: Document) -> dict[str, str | None]:
    head = "\n".join(p.text for p in doc.pages[:3])
    company = None
    m = re.search(r"([^\n]{3,80})\n?\s*\(Exact name of registrant", head, _P)
    if m:
        company = m.group(1).strip()
    period = None
    m = re.search(r"fiscal year ended:?\s*([A-Z][a-z]+ \d{1,2}, \d{4})", head)
    if m:
        period = m.group(1)
    return {"company": company, "period_end": period}


def extract_statement(schema: str, doc: Document):
    """Fill one statement schema from the best-matching page. Returns None if no page fits."""
    best = max(doc.pages, key=lambda p: score_page(schema, p), default=None)
    if best is None or score_page(schema, best) < 2:
        return None
    values: dict = {}
    pages: dict[str, int] = {}
    debt_rows: list[float] = []
    eps_seen = False
    for fld, mode, _label, nums in _match_rows(schema, best):
        if mode == "sum":
            debt_rows.append(nums[0])
        elif mode == "eps":
            # EPS rows are small decimals, share counts are large
            if not eps_seen and abs(nums[0]) < 1000:
                values[fld], pages[fld], eps_seen = nums[0], best.number, True
        elif mode == "capex":
            values[fld] = values.get(fld, 0.0) + abs(nums[0])
            pages[fld] = best.number
        elif fld not in values:
            values[fld], pages[fld] = nums[0], best.number
            if fld in PRIOR and len(nums) > 1:
                values[PRIOR[fld]], pages[PRIOR[fld]] = nums[1], best.number
    if debt_rows:
        values["total_debt"], pages["total_debt"] = sum(debt_rows), best.number
    values.update(doc_facts(doc))
    return STATEMENTS[schema](
        unit=detect_unit(doc, best), source_pages=pages, document=doc.name, **values
    )


def extract_statements(doc: Document) -> dict[str, BaseModel]:
    out = {}
    for name in STATEMENTS:
        got = extract_statement(name, doc)
        if got is not None:
            out[name] = got
    return out


# ---- model based extraction, for invoices, bank statements and anything custom ----

_JSON_RX = re.compile(r"\{.*\}", re.DOTALL)


def parse_json_object(text: str) -> dict:
    """First JSON object in the text. Handles code fences and chatter around it."""
    m = _JSON_RX.search(text)
    if not m:
        raise ValueError("no json object in model output")
    return json.loads(m.group(0))


def schema_hint(schema: type[BaseModel]) -> str:
    props = schema.model_json_schema().get("properties", {})
    return json.dumps({k: v.get("type", v.get("anyOf", "")) for k, v in props.items()}, default=str)


def extract_with_model(schema_name: str, pages: list[Page], backend: Backend, max_tries: int = 2):
    schema = SCHEMAS[schema_name]
    ctx = "\n\n".join(f"[{p.doc} p.{p.number}]\n{p.content[:6000]}" for p in pages)
    system = (
        "You extract fields from documents into JSON. Use only what the text says. "
        "Write numbers as plain numbers without currency signs or commas. "
        "Use null for anything missing. Reply with one JSON object and nothing else."
    )
    user = f"Fields: {schema_hint(schema)}\n\nDocument:\n{ctx}"
    last_err = ""
    for _ in range(max_tries):
        raw = backend.chat(system, user + last_err, None, 900)
        try:
            return schema.model_validate(parse_json_object(raw))
        except (ValueError, ValidationError) as e:
            last_err = (
                f"\n\nYour last reply was invalid ({str(e)[:200]}). Reply with valid JSON only."
            )
    return None
